module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      1,
      'always',
      [
        'api',
        'mobile',
        'vendor-portal',
        'admin-portal',
        'shared-types',
        'api-client',
        'ui',
        'config',
        'infra',
        'ci',
        'docs',
        'deps',
        'db',
        'auth',
        'identity',
        'catalog',
        'files',
        'vendors',
        'inventory',
        'orders',
        'payments',
        'reviews',
        'reels',
        'ai',
        'safety',
        'notifications',
        'weather',
        'transit',
        'realtime',
        'admin',
      ],
    ],
  },
};
